module.exports = [
  {
    season: "1955/1956",
    semiFinal1_1: "Stade Reims",
    semiFinal1_2: "Hiberian FC",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Milan",
    winner: "Real Madrid",
    runnersUp: "Stade Reims",
  },
  {
    season: "1956/1957",
    semiFinal1_1: "Red Star",
    semiFinal1_2: "Fiorentina",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Man Utd",
    winner: "Real Madrid",
    runnersUp: "Fiorentina",
  },
  {
    season: "1957/1958",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Vasas SC",
    semiFinal2_1: "Man Utd",
    semiFinal2_2: "Milan",
    winner: "Real Madrid",
    runnersUp: "Milan",
  },
  {
    season: "1958/1959",
    semiFinal1_1: "BSC Young Boys",
    semiFinal1_2: "Stade Reims",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Atlético Madrid",
    winner: "Real Madrid",
    runnersUp: "Stade Reims",
  },
  {
    season: "1959/1960",
    semiFinal1_1: "E. Frankfurt",
    semiFinal1_2: "Rangers",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Barcelona",
    winner: "Real Madrid",
    runnersUp: "E. Frankfurt",
  },
  {
    season: "1960/1961",
    semiFinal1_1: "Barcelona",
    semiFinal1_2: "Hamburger SV",
    semiFinal2_1: "Benfica",
    semiFinal2_2: "Rapid Vienna",
    winner: "Benfica",
    runnersUp: "Barcelona",
  },
  {
    season: "1961/1962",
    semiFinal1_1: "Benfica",
    semiFinal1_2: "Tottenham",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Standard Liège",
    winner: "Benfica",
    runnersUp: "Real Madrid",
  },
  {
    season: "1962/1963",
    semiFinal1_1: "Feijenoord",
    semiFinal1_2: "Benfica",
    semiFinal2_1: "Milan",
    semiFinal2_2: "Dundee FC",
    winner: "Milan",
    runnersUp: "Benfica",
  },
  {
    season: "1963/1964",
    semiFinal1_1: "Bor. Dortmund",
    semiFinal1_2: "Inter",
    semiFinal2_1: "FC Zürich",
    semiFinal2_2: "Real Madrid",
    winner: "Inter",
    runnersUp: "Real Madrid",
  },
  {
    season: "1964/1965",
    semiFinal1_1: "ETO FC Győr",
    semiFinal1_2: "Benfica",
    semiFinal2_1: "Liverpool",
    semiFinal2_2: "Inter",
    winner: "Inter",
    runnersUp: "Benfica",
  },
  {
    season: "1965/1966",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Inter",
    semiFinal2_1: "Partizan",
    semiFinal2_2: "Man Utd",
    winner: "Real Madrid",
    runnersUp: "Partizan",
  },
  {
    season: "1966/1967",
    semiFinal1_1: "Celtic",
    semiFinal1_2: "Dukla Prague",
    semiFinal2_1: "Inter",
    semiFinal2_2: "CSKA Sofia",
    winner: "Celtic",
    runnersUp: "Inter",
  },
  {
    season: "1967/1968",
    semiFinal1_1: "Man Utd",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "Benfica",
    semiFinal2_2: "Juventus",
    winner: "Man Utd",
    runnersUp: "Benfica",
  },
  {
    season: "1968/1969",
    semiFinal1_1: "Ajax",
    semiFinal1_2: "Spartak Trnava",
    semiFinal2_1: "Milan",
    semiFinal2_2: "Man Utd",
    winner: "Milan",
    runnersUp: "Ajax",
  },
  {
    season: "1969/1970",
    semiFinal1_1: "Leeds",
    semiFinal1_2: "Celtic",
    semiFinal2_1: "Legia Warszawa",
    semiFinal2_2: "Feijenoord",
    winner: "Feijenoord",
    runnersUp: "Celtic",
  },
  {
    season: "1970/1971",
    semiFinal1_1: "Red Star",
    semiFinal1_2: "Panathinaikos",
    semiFinal2_1: "Atlético Madrid",
    semiFinal2_2: "Ajax",
    winner: "Ajax",
    runnersUp: "Panathinaikos",
  },
  {
    season: "1971/1972",
    semiFinal1_1: "Ajax",
    semiFinal1_2: "Benfica",
    semiFinal2_1: "Inter",
    semiFinal2_2: "Celtic",
    winner: "Ajax",
    runnersUp: "Inter",
  },
  {
    season: "1972/1973",
    semiFinal1_1: "Juventus",
    semiFinal1_2: "Derby",
    semiFinal2_1: "Ajax",
    semiFinal2_2: "Real Madrid",
    winner: "Ajax",
    runnersUp: "Juventus",
  },
  {
    season: "1973/1974",
    semiFinal1_1: "Újpesti Dózsa",
    semiFinal1_2: "Bayern Munich",
    semiFinal2_1: "Celtic",
    semiFinal2_2: "Atlético Madrid",
    winner: "Bayern Munich",
    runnersUp: "Atlético Madrid",
  },
  {
    season: "1974/1975",
    semiFinal1_1: "Leeds",
    semiFinal1_2: "FC Barcelona",
    semiFinal2_1: "Saint-Étienne",
    semiFinal2_2: "Bayern Munich",
    winner: "Bayern Munich",
    runnersUp: "Leeds",
  },
  {
    season: "1975/1976",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Bayern Munich",
    semiFinal2_1: "Saint-Étienne",
    semiFinal2_2: "PSV Eindhoven",
    winner: "Bayern Munich",
    runnersUp: "Saint-Étienne",
  },
  {
    season: "1976/1977",
    semiFinal1_1: "FC Zürich",
    semiFinal1_2: "Liverpool",
    semiFinal2_1: "Dynamo Kyiv",
    semiFinal2_2: "Bor. M'gladbach",
    winner: "Liverpool",
    runnersUp: "Bor. M'gladbach",
  },
  {
    season: "1977/1978",
    semiFinal1_1: "Juventus",
    semiFinal1_2: "Club Brugge",
    semiFinal2_1: "Bor. M'gladbach",
    semiFinal2_2: "Liverpool",
    winner: "Liverpool",
    runnersUp: "Club Brugge",
  },
  {
    season: "1978/1979",
    semiFinal1_1: "Nottm Forest",
    semiFinal1_2: "1. FC Köln",
    semiFinal2_1: "Austria Vienna",
    semiFinal2_2: "Malmö FF",
    winner: "Nottm Forest",
    runnersUp: "Malmö FF",
  },
  {
    season: "1979/1980",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Hamburger SV",
    semiFinal2_1: "Nottm Forest",
    semiFinal2_2: "Ajax",
    winner: "Nottm Forest",
    runnersUp: "Hamburger SV",
  },
  {
    season: "1980/1981",
    semiFinal1_1: "Liverpool",
    semiFinal1_2: "Bayern Munich",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Inter",
    winner: "Liverpool",
    runnersUp: "Real Madrid",
  },
  {
    season: "1981/1982",
    semiFinal1_1: "CSKA Sofia",
    semiFinal1_2: "Bayern Munich",
    semiFinal2_1: "Aston Villa",
    semiFinal2_2: "RSC Anderlecht",
    winner: "Aston Villa",
    runnersUp: "Bayern Munich",
  },
  {
    season: "1982/1983",
    semiFinal1_1: "Real Sociedad",
    semiFinal1_2: "Hamburger SV",
    semiFinal2_1: "Juventus",
    semiFinal2_2: "Widzew Lodz",
    winner: "Hamburger SV",
    runnersUp: "Juventus",
  },
  {
    season: "1983/1984",
    semiFinal1_1: "Dundee United",
    semiFinal1_2: "AS Roma",
    semiFinal2_1: "Liverpool",
    semiFinal2_2: "FC Dinamo",
    winner: "Liverpool",
    runnersUp: "AS Roma",
  },
  {
    season: "1984/1985",
    semiFinal1_1: "Juventus",
    semiFinal1_2: "G. Bordeaux",
    semiFinal2_1: "Liverpool",
    semiFinal2_2: "Panathinaikos",
    winner: "Juventus",
    runnersUp: "Liverpool",
  },
  {
    season: "1985/1986",
    semiFinal1_1: "IFK Göteborg",
    semiFinal1_2: "Barcelona",
    semiFinal2_1: "RSC Anderlecht",
    semiFinal2_2: "Steaua Bucharest",
    winner: "Steaua Bucharest",
    runnersUp: "Barcelona",
  },
  {
    season: "1986/1987",
    semiFinal1_1: "Bayern Munich",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "FC Porto",
    semiFinal2_2: "Dynamo Kyiv",
    winner: "FC Porto",
    runnersUp: "Bayern Munich",
  },
  {
    season: "1987/1988",
    semiFinal1_1: "Steaua Bucharest",
    semiFinal1_2: "Benfica",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "PSV Eindhoven",
    winner: "PSV Eindhoven",
    runnersUp: "Benfica",
  },
  {
    season: "1988/1989",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Milan",
    semiFinal2_1: "Steaua Bucharest",
    semiFinal2_2: "Galatasaray",
    winner: "Milan",
    runnersUp: "Steaua Bucharest",
  },
  {
    season: "1989/1990",
    semiFinal1_1: "Milan",
    semiFinal1_2: "Bayern Munich",
    semiFinal2_1: "Marseille",
    semiFinal2_2: "Benfica",
    winner: "Milan",
    runnersUp: "Benfica",
  },
  {
    season: "1990/1991",
    semiFinal1_1: "Bayern Munich",
    semiFinal1_2: "Red Star",
    semiFinal2_1: "Spartak Moscow",
    semiFinal2_2: "Marseille",
    winner: "Red Star",
    runnersUp: "Marseille",
  },
  {
    season: "1993/1994",
    semiFinal1_1: "Barcelona",
    semiFinal1_2: "FC Porto",
    semiFinal2_1: "Milan",
    semiFinal2_2: "Monaco",
    winner: "Milan",
    runnersUp: "Barcelona",
  },
  {
    season: "1994/1995",
    semiFinal1_1: "Bayern Munich",
    semiFinal1_2: "Ajax",
    semiFinal2_1: "Paris SG",
    semiFinal2_2: "Milan",
    winner: "Ajax",
    runnersUp: "Milan",
  },
  {
    season: "1995/1996",
    semiFinal1_1: "Ajax",
    semiFinal1_2: "Panathinaikos",
    semiFinal2_1: "Juventus",
    semiFinal2_2: "FC Nantes",
    winner: "Juventus",
    runnersUp: "Ajax",
  },
  {
    season: "1996/1997",
    semiFinal1_1: "Ajax",
    semiFinal1_2: "Juventus",
    semiFinal2_1: "Bor. Dortmund",
    semiFinal2_2: "Man Utd",
    winner: "Bor. Dortmund",
    runnersUp: "Juventus",
  },
  {
    season: "1997/1998",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Bor. Dortmund",
    semiFinal2_1: "Juventus",
    semiFinal2_2: "Monaco",
    winner: "Real Madrid",
    runnersUp: "Juventus",
  },
  {
    season: "1998/1999",
    semiFinal1_1: "Man Utd",
    semiFinal1_2: "Juventus",
    semiFinal2_1: "Dynamo Kyiv",
    semiFinal2_2: "Bayern Munich",
    winner: "Man Utd",
    runnersUp: "Bayern Munich",
  },
  {
    season: "1999/2000",
    semiFinal1_1: "Valencia",
    semiFinal1_2: "Barcelona",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Bayern Munich",
    winner: "Real Madrid",
    runnersUp: "Valencia",
  },
  {
    season: "2000/2001",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Bayern Munich",
    semiFinal2_1: "Leeds",
    semiFinal2_2: "Valencia",
    winner: "Bayern Munich",
    runnersUp: "Valencia",
  },
  {
    season: "2001/2002",
    semiFinal1_1: "Barcelona",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "Man Utd",
    semiFinal2_2: "B. Leverkusen",
    winner: "Real Madrid",
    runnersUp: "B. Leverkusen",
  },
  {
    season: "2002/2003",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Juventus",
    semiFinal2_1: "Milan",
    semiFinal2_2: "Inter",
    winner: "Milan",
    runnersUp: "Juventus",
  },
  {
    season: "2003/2004",
    semiFinal1_1: "Monaco",
    semiFinal1_2: "Chelsea",
    semiFinal2_1: "FC Porto",
    semiFinal2_2: "Dep. La Coruña",
    winner: "FC Porto",
    runnersUp: "Monaco",
  },
  {
    season: "2004/2005",
    semiFinal1_1: "AC Milan",
    semiFinal1_2: "PSV Eindhoven",
    semiFinal2_1: "Chelsea",
    semiFinal2_2: "Liverpool",
    winner: "Liverpool",
    runnersUp: "AC Milan",
  },
  {
    season: "2005/2006",
    semiFinal1_1: "AC Milan",
    semiFinal1_2: "Barcelona",
    semiFinal2_1: "Arsenal",
    semiFinal2_2: "Villarreal",
    winner: "Barcelona",
    runnersUp: "Arsenal",
  },
  {
    season: "2006/2007",
    semiFinal1_1: "Man Utd",
    semiFinal1_2: "AC Milan",
    semiFinal2_1: "Chelsea",
    semiFinal2_2: "Liverpool",
    winner: "AC Milan",
    runnersUp: "Liverpool",
  },
  {
    season: "2007/2008",
    semiFinal1_1: "Liverpool",
    semiFinal1_2: "Chelsea",
    semiFinal2_1: "Barcelona",
    semiFinal2_2: "Man Utd",
    winner: "Man Utd",
    runnersUp: "Chelsea",
  },
  {
    season: "2008/2009",
    semiFinal1_1: "Barcelona",
    semiFinal1_2: "Chelsea",
    semiFinal2_1: "Man Utd",
    semiFinal2_2: "Arsenal",
    winner: "Barcelona",
    runnersUp: "Man Utd",
  },
  {
    season: "2009/2010",
    semiFinal1_1: "Inter",
    semiFinal1_2: "Barcelona",
    semiFinal2_1: "Bayern Munich",
    semiFinal2_2: "Olympique Lyon",
    winner: "Inter",
    runnersUp: "Bayern Munich",
  },
  {
    season: "2010/2011",
    semiFinal1_1: "FC Schalke 04",
    semiFinal1_2: "Man Utd",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Barcelona",
    winner: "Barcelona",
    runnersUp: "Man Utd",
  },
  {
    season: "2011/2012",
    semiFinal1_1: "Bayern Munich",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "Chelsea",
    semiFinal2_2: "Barcelona",
    winner: "Chelsea",
    runnersUp: "Bayern Munich",
  },
  {
    season: "2012/2013",
    semiFinal1_1: "Bayern Munich",
    semiFinal1_2: "Barcelona",
    semiFinal2_1: "Bor. Dortmund",
    semiFinal2_2: "Real Madrid",
    winner: "Bayern Munich",
    runnersUp: "Bor. Dortmund",
  },
  {
    season: "2013/2014",
    semiFinal1_1: "Atlético Madrid",
    semiFinal1_2: "Chelsea",
    semiFinal2_1: "Real Madrid",
    semiFinal2_2: "Bayern Munich",
    winner: "Real Madrid",
    runnersUp: "Atlético Madrid",
  },
  {
    season: "2014/2015",
    semiFinal1_1: "Juventus",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "Barcelona",
    semiFinal2_2: "Bayern Munich",
    winner: "Barcelona",
    runnersUp: "Juventus",
  },
  {
    season: "2015/2016",
    semiFinal1_1: "Man City",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "Atlético Madrid",
    semiFinal2_2: "Bayern Munich",
    winner: "Real Madrid",
    runnersUp: "Atlético Madrid",
  },
  {
    season: "2016/2017",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Atlético Madrid",
    semiFinal2_1: "Monaco",
    semiFinal2_2: "Juventus",
    winner: "Real Madrid",
    runnersUp: "Juventus",
  },
  {
    season: "2017/2018",
    semiFinal1_1: "Liverpool",
    semiFinal1_2: "AS Roma",
    semiFinal2_1: "Bayern Munich",
    semiFinal2_2: "Real Madrid",
    winner: "Real Madrid",
    runnersUp: "Liverpool",
  },
  {
    season: "2018/2019",
    semiFinal1_1: "Tottenham",
    semiFinal1_2: "Ajax",
    semiFinal2_1: "Barcelona",
    semiFinal2_2: "Liverpool",
    winner: "Liverpool",
    runnersUp: "Tottenham",
  },
  {
    season: "2019/2020",
    semiFinal1_1: "RB Leipzig",
    semiFinal1_2: "Paris SG",
    semiFinal2_1: "Olympique Lyon",
    semiFinal2_2: "Bayern Munich",
    winner: "Bayern Munich",
    runnersUp: "Paris SG",
  },
  {
    season: "2020/2021",
    semiFinal1_1: "Real Madrid",
    semiFinal1_2: "Chelsea",
    semiFinal2_1: "Paris SG",
    semiFinal2_2: "Man City",
    winner: "Chelsea",
    runnersUp: "Man City",
  },
  {
    season: "2021/2022",
    semiFinal1_1: "Man City",
    semiFinal1_2: "Real Madrid",
    semiFinal2_1: "Liverpool",
    semiFinal2_2: "Villarreal",
    winner: "Real Madrid",
    runnersUp: "Liverpool",
  },
];
